# Generated by Django 3.2.6 on 2021-08-29 06:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('online_judge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
    ]
